apiVersion: v2
name: wasp-payload-parser-oyster2
appVersion: '1.0.3'
description: A Helm chart for wasp-payload-parser-oyster2
version: '1.0.3'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: kafka
    version: '12.7.3'
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: nginx
    alias: waspthingmock
    version: '^8.7.1'
    repository: https://charts.bitnami.com/bitnami
    condition: waspthingmock.enabled
