apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-payload-parser-oyster2.fullname" . }}-config
  labels:
    {{- include "wasp-payload-parser-oyster2.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  waspSensor: {{ .Values.config.waspSensorType }}
  logLevel: {{ .Values.config.logLevel }}
  kafkaLogLevel: {{ .Values.config.kafkajsLogLevel }}
  kafkaBrokers: {{ include "wasp-payload-parser-oyster2.kafka.brokers" . }}
  kafkaReadingsTopic: {{ .Values.config.kafkaReadingsTopic }}
  kafkaEventsTopic: {{ .Values.config.kafkaEventsTopic }}
  kafkaPayloadRoutingPrefix: {{ .Values.config.kafkaPayloadRoutingPrefix }}
  kafkaPayloadsPartitions: {{ .Values.config.kafkaPayloadsPartitions | quote }}
  kafkaPayloadsReplicationFactor: {{ .Values.config.kafkaPayloadsReplicationFactor | quote }}
