{{- $fullName := include "wasp-payload-parser-oyster2.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: wasp-payload-parser-oyster2
  labels:
    {{- include "wasp-payload-parser-oyster2.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ include "wasp-payload-parser-oyster2.fullname" . }}
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: {{ .Values.config.port }}
